export const products = [
    {
        _id: "1",
        name: "Phantom 4 Pro",
        image: "/images/Phantom.png",
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate possimus suscipit dicta nostrum ad aliquid itaque doloribus accusantium iusto quod fugiat officiis debitis nulla aliquam ex at dignissimos voluptatem, distinctio, in esse atque quibusdam asperiores voluptates! Vero ea animi quidem iste sit ducimus, aspernatur vitae, optio deserunt id in officiis!',
        brand: "DJI",
        category: "Hobbyist",
        price: 1399.99,
        countInStock: 3,
        rating: 4.9,
        numReviews: 20
    },
    {
        _id: "2",
        name: "Predator",
        image: "/images/Predator.png",
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate possimus suscipit dicta nostrum ad aliquid itaque doloribus accusantium iusto quod fugiat officiis debitis nulla aliquam ex at dignissimos voluptatem, distinctio, in esse atque quibusdam asperiores voluptates! Vero ea animi quidem iste sit ducimus, aspernatur vitae, optio deserunt id in officiis!',
        brand: "General Atomics",
        category: "Military",
        price: 3000000.00,
        countInStock: 3,
        rating: 4.4,
        numReviews: 22
    },
    {
        _id: "3",
        name: "RQ-4 Global Hawk",
        image: "/images/military.png",
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate possimus suscipit dicta nostrum ad aliquid itaque doloribus accusantium iusto quod fugiat officiis debitis nulla aliquam ex at dignissimos voluptatem, distinctio, in esse atque quibusdam asperiores voluptates! Vero ea animi quidem iste sit ducimus, aspernatur vitae, optio deserunt id in officiis!',
        brand: "Northrop Grumman",
        category: "Military",
        price: 131400000.00,
        countInStock: 0,
        rating: 5.0,
        numReviews: 1
    },
    {
        _id: "4",
        name: "Mavic 2",
        image: "/images/mavic.png",
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate possimus suscipit dicta nostrum ad aliquid itaque doloribus accusantium iusto quod fugiat officiis debitis nulla aliquam ex at dignissimos voluptatem, distinctio, in esse atque quibusdam asperiores voluptates! Vero ea animi quidem iste sit ducimus, aspernatur vitae, optio deserunt id in officiis!',
        brand: "DJI",
        category: "Hobbyist",
        price: 699.99,
        countInStock: 9,
        rating: 4.7,
        numReviews: 34
    },
    {
        _id: "5",
        name: "Inspire 2",
        image: "/images/inspire2.png",
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate possimus suscipit dicta nostrum ad aliquid itaque doloribus accusantium iusto quod fugiat officiis debitis nulla aliquam ex at dignissimos voluptatem, distinctio, in esse atque quibusdam asperiores voluptates! Vero ea animi quidem iste sit ducimus, aspernatur vitae, optio deserunt id in officiis!',
        brand: "DJI",
        category: "Professional",
        price: 2399.99,
        countInStock: 2,
        rating: 4.4,
        numReviews: 3
    },
    {
        _id: "6",
        name: "ESO",
        image: "/images/ESO.png",
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate possimus suscipit dicta nostrum ad aliquid itaque doloribus accusantium iusto quod fugiat officiis debitis nulla aliquam ex at dignissimos voluptatem, distinctio, in esse atque quibusdam asperiores voluptates! Vero ea animi quidem iste sit ducimus, aspernatur vitae, optio deserunt id in officiis!',
        brand: "Custom",
        category: "Professional",
        price: 4499.99,
        countInStock: 1,
        rating: 4.9,
        numReviews: 2
    },
    {
        _id: "7",
        name: "Custom 2",
        image: "/images/Phantom.png",
        description: 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Voluptate possimus suscipit dicta nostrum ad aliquid itaque doloribus accusantium iusto quod fugiat officiis debitis nulla aliquam ex at dignissimos voluptatem, distinctio, in esse atque quibusdam asperiores voluptates! Vero ea animi quidem iste sit ducimus, aspernatur vitae, optio deserunt id in officiis!',
        brand: "Custom",
        category: "Professional",
        price: 6999.99,
        countInStock: 1,
        rating: 4.3,
        numReviews: 1
    },
]